PASS_MESSAGE = "The test passed successfully"
VERSION = "0.0"
SUITE_PASSED_ATTRIBUTE = "passed"
SUITE_VERSION_ATTRIBUTE = "suite-version"
FORBIDDEN_TEST_NAMES = [SUITE_PASSED_ATTRIBUTE, SUITE_VERSION_ATTRIBUTE]
