name: pull-check
run-name: pullCheck
on:
  pull_request:
    types: [ labeled ]

jobs:
  test-request-file:
    if: ${{ github.event.label.name.contains('add model:' }}
    runs-on: ubuntu-latest

    
