name: pull-check
run-name: pullCheck
on:
   workflow_dispatch:
  #pull_request:
   # types: [ labeled, opened ]
jobs:
  Test-request-file:
    #if: ${{ github.event.label.name.contains('add model:') }
    if: github.event.pull_request.base.ref == 'master' # check the target branch if it's master
    runs-on: ubuntu-latest
    steps:
        - name: test
          run: echo "Hii"
  Job2:
    if: github.event.pull_request.base.ref != 'master' # check the target branch if it's master
    runs-on: self-hosted
    steps:  
        - name: checkout main branch
          uses: actions/checkout@v4
          with: 
               ref: main
        - name: run-submission-file-tests
          run: repository=$(conda run -n ewatercycle --no-capture-output python PluginSubmissionTests.py)   
        - name: check-for-correct-repo-name
          run: echo $repository
        - name: clone-repo
          uses: actions/checkout@v4
          with:
              ref: main
              repository: $repository
        - name: checkout
          run: git checkout main
        - name: test
          run: echo "Hello"
        - name: run-model-tests
          run: conda run -n ewatercycle --no-capture-output python main.py

