name: pull-check
run-name: pullCheck
on:
   workflow_dispatch:
   pull_request:
       types: [ labeled, reopened, opened ]
jobs:
  Test-request-file:
    if: ${{ github.event.label.name == 'add model'}} |
        github.event.pull_request.base.ref == 'master' # check the target branch if it's master
    runs-on: self-hosted
    steps:
        - name: checkout main branch
          uses: actions/checkout@v4
          with: 
               ref: ${{github.head_ref}}
        - name: test
          run: ls
        - name: create-new-directory
          run: mkdir second
        - name: submission-file-tests
          run: echo "repository=$(conda run -n ewatercycle --no-capture-output python PluginSubmissionTests.py)" >> "$GITHUB_ENV"  
        - name: clone-repo
          uses: actions/checkout@v4
          with:
              ref: main
              repository: ${{steps.submission-file-tests.outputs.repository}}
              path: second
              token : ${{ secrets.TOKEN1 }}
        - name: move file
          run: mv -f second/Mocks.py .
        - name: test2
          run: ls
  Test-model:
    needs: Test-request-file
    if: ${{ github.event.label.name == 'add model' }} |
        github.event.pull_request.base.ref == 'master'
    runs-on: self-hosted
    steps:  
        - name: clone-repo
          uses: actions/checkout@v4
          with:
              ref: main
              repository: ${{steps.submission-file-tests.outputs.repository}}
              path: second
              token : ${{ secrets.TOKEN1 }}
        - name: run-model-tests
          run: echo conda run -n ewatercycle --no-capture-output python second/main.py
        - name: stash-test-result
          run: mv second/output/testReport.yaml .
        - name: configure-credentials
          uses: oleksiyrudenko/gha-git-credentials@v2-latest
          with:
                token: '${{ secrets.GITHUB_TOKEN }}'
        - name: commit-test-results
          run: |
              git config --global user.name "maselko13"
              git config --global user.email "konrad.gniaz@wp.pl"
              git add testReport.yaml
              git commit -m "Add test results"
              git push
