name: pull-check
run-name: pullCheck
on:
   workflow_dispatch:
  #pull_request:
   # types: [ labeled, opened ]

jobs:
  Test-request-file:
    #if: ${{ github.event.label.name.contains('add model:') }
    runs-on: ubuntu-latest
    steps:
        - name: test
          run: echo "Hii"
  Job2:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref != 'master' # check the target branch if it's master
    steps:
        - name: trigger
          run: echo "Hello"
