name: pull-check
run-name: pullCheck
on:
   workflow_dispatch:
   pull_request:
       types: [ labeled, reopened, opened ]
jobs:
  Test-request-file:
    if: startsWith(github.event.pull_request.title, 'add model:') &&  github.event.pull_request.base.ref == 'main' 
    runs-on: self-hosted
    steps:
        - name: configure-credentials
          uses: oleksiyrudenko/gha-git-credentials@v2-latest
          with:
                global: true
                name: 'maselko13'
                email: 'konrad.gniaz@wp.pl'
                token: '${{ secrets.GITHUB_TOKEN }}'
        - name: checkout main branch
          uses: actions/checkout@v4
          with: 
               ref: ${{github.head_ref}}
        - name: create-new-directory
          run: mkdir second
        - name: test33
          run: conda run -n ewatercycle --no-capture-output python PluginSubmissionTests.py
        - name: submission-file-tests
          run: echo "repository=$(conda run -n ewatercycle --no-capture-output python PluginSubmissionTests.py)" >> "$GITHUB_ENV" 
        - name: test1
          run: echo ${{steps.submission-file-tests.outputs.repository}}
        - name: clone-repo
          uses: actions/checkout@v4
          with:
              repository: ${{steps.submission-file-tests.outputs.repository}}
              ref: main
              path: second
        - name: move file
          run: mv -f second/Mocks.py .
        - name: test2
          run: ls
  Test-model:
    needs: Test-request-file
    if: startsWith(github.event.pull_request.title, 'add model:') &&  github.event.pull_request.base.ref == 'main' 
    runs-on: self-hosted
    permissions:
      contents: write
    steps:  
        - name: clone-repo
          uses: actions/checkout@v4
          with:
              ref: main
              repository: ${{steps.submission-file-tests.outputs.repository}}
              path: second
        - name: run-model-tests
          run: echo conda run -n ewatercycle --no-capture-output python second/main.py
        - name: stash-test-result
          run: mv second/output/testReport.yaml .
        - name: commit-test-results
          run: |
              git add testReport.yaml
              git commit -m "Add test results"
              git -c credential.helper='!f() { echo "username=maselko13"; echo "password=${{secrets.TOKEN1}}"; }; f' push
