name: pull-check
run-name: pullCheck
on:
   workflow_dispatch:
   pull_request:
       types: [ labeled, opened ]
jobs:
  Test-request-file:
    if: ${{ github.event.label.name == 'add model'}} |
        github.event.pull_request.base.ref == 'master' # check the target branch if it's master
    runs-on: self-hosted
    steps:
        - name: checkout main branch
          uses: actions/checkout@v4
          with: 
               ref: ${{github.head_ref}}
        - name: create-new-directory
          run: mkdir second
        - name: submission-file-tests
          run: echo "repository=$(conda run -n ewatercycle --no-capture-output python submission.py)" >> "$GITHUB_ENV"  
        - name: clone-repo
          uses: actions/checkout@v4
          with:
              ref: main
              repository: ${{steps.submission-file-tests.outputs.repository}}
              path: second
        - name: move-to-directory
          run: cd second
        - name: move file
          run: mv -f Mocks.py ..
        - name: move-back
          run: cd ..
  Test-model:
    needs: Test-request-file
    if: ${{ github.event.label.name == 'add model' }} |
        github.event.pull_request.base.ref == 'master'
    runs-on: self-hosted
    steps:  
        - name: run-model-tests
          run: echo "message=$(conda run -n ewatercycle --no-capture-output python second/main.py)" >> "$GITHUB_ENV"
        - name: stash-test-result
          run: git add second/output/testReport.yaml
        - name: commit-test-results
          run: git commit -m "Add test results"
        - name: push-addition
          run: git push
